/*

Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

*/
const fib = [1, 2]
function fiboEvenSum(n) {

    while (fib[fib.length - 1] + fib[fib.length - 2]
        <= n) {
        fib.push(fib[fib.length - 1] + fib[fib.length - 2]);
    }

    return fib.reduce((sum, num) => num % 2 === 0 ? sum + num : sum, 0);

}

console.log(fiboEvenSum(8));

